# Generated by Django 4.2.1 on 2023-06-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_email_alter_user_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="referal_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
