# Generated by Django 3.2.2 on 2023-10-19 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_bal', models.FloatField(default=0.0)),
                ('bonus_bal', models.FloatField(default=0.0)),
                ('winning_amount', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('message', models.TextField(blank=True)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('action', models.IntegerField(choices=[(1, 'Credit'), (2, 'Debit')])),
                ('credit_type', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw'), (3, 'Bonus'), (4, 'Winning'), (5, 'Contest'), (6, 'Refund')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tds', models.FloatField(blank=True, null=True)),
                ('meta_data', models.JSONField(null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('referer', 'user')},
            },
        ),
    ]
