# Generated by Django 4.2.1 on 2023-06-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning",
            "0002_answer_bookmark_pages_question_watchlist_quiz_atempt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="book_page",
            field=models.IntegerField(default=0),
        ),
    ]
