# Generated by Django 4.2.1 on 2023-07-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_category_level_extra_field_course_category"),
    ]

    operations = [
        migrations.AlterModelOptions(name="pages", options={"ordering": ("page_no",)},),
    ]
