# Generated by Django 3.2.2 on 2023-08-02 16:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('entry_amount', models.IntegerField()),
                ('user_spot', models.IntegerField()),
                ('total_spot', models.IntegerField()),
                ('winner', models.IntegerField()),
                ('payout_done', models.BooleanField(default=False)),
                ('pool_size', models.IntegerField()),
                ('filled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BattleEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('winning', models.IntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(default='stock_image/defaut.png', upload_to='stock_image')),
                ('current_price', models.IntegerField(default=0)),
                ('movement', models.PositiveSmallIntegerField(choices=[(1, 'Up'), (2, 'Down')])),
                ('move', models.FloatField(default=0.0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='battle.stockcategory')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battle.stockvariant')),
            ],
        ),
        migrations.CreateModel(
            name='RankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower', models.IntegerField()),
                ('upper', models.IntegerField(null=True)),
                ('amount', models.IntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battle')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('points', models.IntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battle')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueBattleBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battleenrolment')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattleEnrolmentBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_multiplier', models.BooleanField(default=False)),
                ('second_multiplier', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battleenrolment')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.answer')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battletype'),
        ),
        migrations.AddField(
            model_name='battle',
            name='contest_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.contesttype'),
        ),
        migrations.AddField(
            model_name='battle',
            name='stocks_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.stockvariant'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.question'),
        ),
    ]
