# Generated by Django 4.2.1 on 2023-07-18 18:18

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField()),
                ("correct", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contest_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Head To Head"), (2, "Practi")], db_index=True
                    ),
                ),
                (
                    "stocks_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Indian Stock"), (2, "US Stock"), (3, "Crypto")],
                        db_index=True,
                    ),
                ),
                (
                    "battle_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Predict Battle"),
                            (2, "Time Battle"),
                            (3, "League Battle"),
                            (4, "Solo Battle"),
                        ],
                        db_index=True,
                    ),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField()),
                ("entry_amount", models.IntegerField()),
                ("user_spot", models.IntegerField()),
                ("total_spot", models.IntegerField()),
                ("winner", models.IntegerField()),
                ("payout_done", models.BooleanField(default=False)),
                ("pool_size", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BattleEnrolment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("rank", models.IntegerField()),
                ("winning", models.IntegerField()),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="battle.battle"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RankCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lower", models.IntegerField()),
                ("upper", models.IntegerField(null=True)),
                ("amount", models.IntegerField()),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="battle.battle"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField()),
                ("points", models.IntegerField()),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="battle.battle"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BattleEnrolmentBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_multiplier", models.BooleanField(default=False)),
                ("second_multiplier", models.BooleanField(default=False)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battle.battleenrolment",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="battle.answer"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="battle.question"
            ),
        ),
    ]
