# Generated by Django 4.2.1 on 2023-07-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BattleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="battle",
            name="filled",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="battle",
            name="battle_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="battle.battletype"
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="contest_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="battle.contesttype"
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="stocks_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="battle.stockvariant"
            ),
        ),
    ]
