# Generated by Django 4.2.1 on 2023-07-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0002_battletype_contesttype_stockvariant_battle_filled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="stock_image/defaut.png", upload_to="stock_image"
                    ),
                ),
                ("current_price", models.IntegerField(default=0)),
                (
                    "movement",
                    models.PositiveSmallIntegerField(choices=[(1, "Up"), (2, "Down")]),
                ),
                ("move", models.FloatField(default=0.0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="battle.stockcategory",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="battle.stockvariant",
                    ),
                ),
            ],
        ),
    ]
