# Generated by Django 4.2.1 on 2023-07-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0003_stockcategory_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="name",
            field=models.CharField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
